# Robot Parameters

# base_link_mass: 2.0 # Revisit alater
base_length: 0.154
base_width: 0.204
base_height: 0.092
base_link_offset: -0.074
base_wheel_gap_z: 0.06
base_collision: false

wheel_mass: 0.033         # 33g
wheel_radius: 0.034       # 6.8cm wheelDia
wheel_offset_z: 0.039    # 6.4cm from base_link
wheel_thickness: 0.02     # 2cm 
wheel_separation: 0.1934

caster_wheel_mass: 0.04       # 40g
caster_wheel_radius: 0.0105   # 2.1cm casterHeight
caster_wheel_thickness: 0.02
# caster_wheel_seperation: 0.42
caster_offset_z: -0.062  # From Robot Center
caster_offset_y: 0.07967 #Must be -ve if behind base_link

lidar_box_mass: 0.050
lidar_box_size: 0.05